name: poetic_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # google_fonts: ^2.3.1
  #
  # Firebase  remote database
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  firebase_auth: ^2.0.0
  cloud_firestore: ^3.1.10
  firebase_messaging: ^11.2.11
  #
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  provider: ^6.0.1
  uuid: ^3.0.5
  flutter_staggered_grid_view: ^0.6.1
  #
  flutter_quill: ^4.0.8
  tuple: ^2.0.0
  video_player: ^2.2.16
  file_picker: ^4.5.1
  #
  audioplayers: ^0.20.1
  #
  flutter_material_color_picker: ^1.1.0+2
  share_plus: ^4.0.1
  screenshot: ^1.2.3
  #NOTIFICATION
  flutter_local_notifications: ^9.4.0
  flutter_svg: ^1.0.3
  #
  http: ^0.13.4
  path_provider: ^2.0.9 #2.0.12
  #theam
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  # Charts
  syncfusion_flutter_charts: ^19.4.56
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  #
  # flutter_downloader: ^1.7.4
  # dio: ^4.0.6
  # open_file: ^3.2.1
  permission_handler: ^9.2.0
  # sizer: ^2.0.15
  # android_path_provider: ^0.3.0
  # flutter_localizations: # Add this line
  #   sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true # Add this line

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/image/
    - assets/svg/
    - assets/CountryCodes.json
    - assets/AccountTypes.json
    - assets/Interests.json
    - assets/countries.json
    - assets/languages.json

  fonts:
    - family: avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 700
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 300

    - family: AppSymbols
      fonts:
        - asset: assets/fonts/AppSymbols.ttf
    # new added
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-VariableFont.ttf
    - family: ZenLoop
      fonts:
        - asset: assets/fonts/ZenLoop-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
    - family: Macondo
      fonts:
        - asset: assets/fonts/Macondo-Regular.ttf
    - family: Koulen
      fonts:
        - asset: assets/fonts/Koulen-Regular.ttf

      # new added
    - family: TW CEN MT
      fonts:
        - asset: assets/fonts/TCB.ttf
        - asset: assets/fonts/TCM.ttf

    - family: Hurricane
      fonts:
        - asset: assets/fonts/Hurricane-Regular.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Medium.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
    - family: Teko
      fonts:
        - asset: assets/fonts/Teko-Medium.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
    - family: RubikMoonrocks
      fonts:
        - asset: assets/fonts/RubikMoonrocks-Regular.ttf
    - family: Parnaso
      fonts:
        - asset: assets/fonts/Parnaso-Italic.ttf
          style: italic
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

    - family: AbovetheBeyondSerif
      fonts:
        - asset: assets/fonts/AbovetheBeyondSerif-Italic.ttf
          style: italic
